[package]
authors = ["luowen <757130778@qq.com>"]
edition = "2021"
name = "rcli"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.5.11", features = ["derive"]}
csv = "1.3.0"
serde = {version = "1.0.204", features = ["derive"]}
