[advisories]
# 禁止任何带有已知安全漏洞的依赖项
unmaintained = true
[licenses]
# 允许使用 MIT 或 Apache-2.0 许可证的依赖项
allowed = ["MIT", "Apache-2.0"]

# 禁止使用 GPL（GNU General Public License）许可证的依赖项
forbidden = ["GPL-*"]
[sources]
# 仅允许从 crates.io 获取依赖项
allowed = ["registry+https://github.com/rust-lang/crates.io-index"]

# 禁止从 Git 仓库或其他不受信任的源获取依赖项
forbidden = ["git+*"]
